// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udancjbrgsrnbhhuwmef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkYW5jamJyZ3NybmJoaHV3bWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODc5MjYsImV4cCI6MjA2NjY2MzkyNn0.4smJtSTPIFrlRr__gDkjZ1VYNEsdOMHiLGLUbALYVr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);